bridges:
  eth_cable_1:
    members:
      - type: dut
        dut_name: bedroom_model-g
        dut_port: eth1
      - type: dut
        dut_name: garage_model-c
        dut_port: eth0
    wan: null
  eth_cable_2:
    members:
      - type: dut
        dut_name: garage_model-c
        dut_port: eth1
      - type: dut
        dut_name: bedroom_model-d
        dut_port: eth0
    wan: null
  eth_cable_3:
    members:
      - type: sim_wired_client
        pod: bedroom4
        namespace: bedroom4_sim_wired_client
      - type: dut
        dut_name: bedroom_model-d
        dut_port: eth1
    wan: null
  internet_connection:
    members:
      - type: dut
        dut_name: bedroom_model-g
        dut_port: eth0
    wan: bedroom
sim_wireless_clients:
  - pod: bedroom4
    phy: phy1
    namespace: bedroom_5G
power_on: []
